from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Optional

from database.db import get_db
from database.crud import (
    get_watchlists,
    get_watchlist_by_id,
    create_watchlist,
    add_category_to_watchlist,
    add_repository_to_watchlist,
    remove_category_from_watchlist,
    remove_repository_from_watchlist,
    get_alerts,
    get_alert_by_id,
    mark_alert_read,
)
from database.schemas import (
    WatchlistCreate,
    WatchlistOut,
    WatchlistCategoryOut,
    WatchlistRepositoryOut,
    AlertOut,
)
from intelligence.watchlist_engine import analyze_single_watchlist_alerts

router = APIRouter(tags=["Watchlists"])


# ==========================================
# WATCHLIST ENDPOINTS
# ==========================================
@router.get("/watchlists", response_model=List[WatchlistOut])
def list_watchlists(db: Session = Depends(get_db)):
    return get_watchlists(db)


@router.post("/watchlists", response_model=WatchlistOut)
def create_new_watchlist(watchlist: WatchlistCreate, db: Session = Depends(get_db)):
    return create_watchlist(db, name=watchlist.name, description=watchlist.description)


@router.get("/watchlists/{watchlist_id}", response_model=WatchlistOut)
def get_watchlist(watchlist_id: int, db: Session = Depends(get_db)):
    watchlist = get_watchlist_by_id(db, watchlist_id)
    if not watchlist:
        raise HTTPException(status_code=404, detail="Watchlist not found")
    return watchlist


@router.post(
    "/watchlists/{watchlist_id}/categories/{category_id}",
    response_model=WatchlistCategoryOut,
)
def add_category(watchlist_id: int, category_id: int, db: Session = Depends(get_db)):
    watchlist = get_watchlist_by_id(db, watchlist_id)
    if not watchlist:
        raise HTTPException(status_code=404, detail="Watchlist not found")
    return add_category_to_watchlist(db, watchlist_id, category_id)


@router.delete("/watchlists/{watchlist_id}/categories/{category_id}")
def remove_category(watchlist_id: int, category_id: int, db: Session = Depends(get_db)):
    watchlist = get_watchlist_by_id(db, watchlist_id)
    if not watchlist:
        raise HTTPException(status_code=404, detail="Watchlist not found")
    remove_category_from_watchlist(db, watchlist_id, category_id)
    return {"status": "removed"}


@router.post(
    "/watchlists/{watchlist_id}/repositories/{repository_id}",
    response_model=WatchlistRepositoryOut,
)
def add_repository(watchlist_id: int, repository_id: int, db: Session = Depends(get_db)):
    watchlist = get_watchlist_by_id(db, watchlist_id)
    if not watchlist:
        raise HTTPException(status_code=404, detail="Watchlist not found")
    return add_repository_to_watchlist(db, watchlist_id, repository_id)


@router.delete("/watchlists/{watchlist_id}/repositories/{repository_id}")
def remove_repository(
    watchlist_id: int, repository_id: int, db: Session = Depends(get_db)
):
    watchlist = get_watchlist_by_id(db, watchlist_id)
    if not watchlist:
        raise HTTPException(status_code=404, detail="Watchlist not found")
    remove_repository_from_watchlist(db, watchlist_id, repository_id)
    return {"status": "removed"}


@router.post("/watchlists/{watchlist_id}/scan", response_model=List[AlertOut])
def scan_watchlist(watchlist_id: int, db: Session = Depends(get_db)):
    """
    Trigger spike detection for a single watchlist.

    Runs momentum, star-growth, and signal-activity analysis across all
    tracked categories and repositories.  Returns only the *new* alerts
    generated by this scan; previously raised alerts within the 24-hour
    cooldown window are suppressed.
    """
    watchlist = get_watchlist_by_id(db, watchlist_id)
    if not watchlist:
        raise HTTPException(status_code=404, detail="Watchlist not found")
    alerts = analyze_single_watchlist_alerts(db, watchlist)
    return alerts


# ==========================================
# ALERT ENDPOINTS
# ==========================================
@router.get("/alerts", response_model=List[AlertOut])
def list_alerts(
    watchlist_id: Optional[int] = None,
    severity: Optional[str] = None,
    is_read: Optional[bool] = False,
    limit: int = 50,
    db: Session = Depends(get_db),
):
    return get_alerts(db, watchlist_id=watchlist_id, severity=severity, is_read=is_read, limit=limit)


@router.get("/alerts/{alert_id}", response_model=AlertOut)
def get_alert(alert_id: int, db: Session = Depends(get_db)):
    alert = get_alert_by_id(db, alert_id)
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    return alert


@router.post("/alerts/{alert_id}/read")
def read_alert(alert_id: int, db: Session = Depends(get_db)):
    alert = mark_alert_read(db, alert_id)
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    return {"status": "marked_read"}